# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yy/singleODS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yy/singleODS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yy/singleODS/CMakeFiles /home/yy/singleODS/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yy/singleODS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_omap

# Build rule for target.
test_omap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_omap
.PHONY : test_omap

# fast build rule for target.
test_omap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/build
.PHONY : test_omap/fast

src/AES.o: src/AES.cpp.o

.PHONY : src/AES.o

# target to build an object file
src/AES.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/AES.cpp.o
.PHONY : src/AES.cpp.o

src/AES.i: src/AES.cpp.i

.PHONY : src/AES.i

# target to preprocess a source file
src/AES.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/AES.cpp.i
.PHONY : src/AES.cpp.i

src/AES.s: src/AES.cpp.s

.PHONY : src/AES.s

# target to generate assembly for a file
src/AES.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/AES.cpp.s
.PHONY : src/AES.cpp.s

src/AVLTree.o: src/AVLTree.cpp.o

.PHONY : src/AVLTree.o

# target to build an object file
src/AVLTree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/AVLTree.cpp.o
.PHONY : src/AVLTree.cpp.o

src/AVLTree.i: src/AVLTree.cpp.i

.PHONY : src/AVLTree.i

# target to preprocess a source file
src/AVLTree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/AVLTree.cpp.i
.PHONY : src/AVLTree.cpp.i

src/AVLTree.s: src/AVLTree.cpp.s

.PHONY : src/AVLTree.s

# target to generate assembly for a file
src/AVLTree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/AVLTree.cpp.s
.PHONY : src/AVLTree.cpp.s

src/Bid.o: src/Bid.cpp.o

.PHONY : src/Bid.o

# target to build an object file
src/Bid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/Bid.cpp.o
.PHONY : src/Bid.cpp.o

src/Bid.i: src/Bid.cpp.i

.PHONY : src/Bid.i

# target to preprocess a source file
src/Bid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/Bid.cpp.i
.PHONY : src/Bid.cpp.i

src/Bid.s: src/Bid.cpp.s

.PHONY : src/Bid.s

# target to generate assembly for a file
src/Bid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/Bid.cpp.s
.PHONY : src/Bid.cpp.s

src/OMAP.o: src/OMAP.cpp.o

.PHONY : src/OMAP.o

# target to build an object file
src/OMAP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/OMAP.cpp.o
.PHONY : src/OMAP.cpp.o

src/OMAP.i: src/OMAP.cpp.i

.PHONY : src/OMAP.i

# target to preprocess a source file
src/OMAP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/OMAP.cpp.i
.PHONY : src/OMAP.cpp.i

src/OMAP.s: src/OMAP.cpp.s

.PHONY : src/OMAP.s

# target to generate assembly for a file
src/OMAP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/OMAP.cpp.s
.PHONY : src/OMAP.cpp.s

src/ORAM.o: src/ORAM.cpp.o

.PHONY : src/ORAM.o

# target to build an object file
src/ORAM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/ORAM.cpp.o
.PHONY : src/ORAM.cpp.o

src/ORAM.i: src/ORAM.cpp.i

.PHONY : src/ORAM.i

# target to preprocess a source file
src/ORAM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/ORAM.cpp.i
.PHONY : src/ORAM.cpp.i

src/ORAM.s: src/ORAM.cpp.s

.PHONY : src/ORAM.s

# target to generate assembly for a file
src/ORAM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/ORAM.cpp.s
.PHONY : src/ORAM.cpp.s

src/RAMStore.o: src/RAMStore.cpp.o

.PHONY : src/RAMStore.o

# target to build an object file
src/RAMStore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/RAMStore.cpp.o
.PHONY : src/RAMStore.cpp.o

src/RAMStore.i: src/RAMStore.cpp.i

.PHONY : src/RAMStore.i

# target to preprocess a source file
src/RAMStore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/RAMStore.cpp.i
.PHONY : src/RAMStore.cpp.i

src/RAMStore.s: src/RAMStore.cpp.s

.PHONY : src/RAMStore.s

# target to generate assembly for a file
src/RAMStore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/src/RAMStore.cpp.s
.PHONY : src/RAMStore.cpp.s

test_omap.o: test_omap.cpp.o

.PHONY : test_omap.o

# target to build an object file
test_omap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/test_omap.cpp.o
.PHONY : test_omap.cpp.o

test_omap.i: test_omap.cpp.i

.PHONY : test_omap.i

# target to preprocess a source file
test_omap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/test_omap.cpp.i
.PHONY : test_omap.cpp.i

test_omap.s: test_omap.cpp.s

.PHONY : test_omap.s

# target to generate assembly for a file
test_omap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_omap.dir/build.make CMakeFiles/test_omap.dir/test_omap.cpp.s
.PHONY : test_omap.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_omap"
	@echo "... src/AES.o"
	@echo "... src/AES.i"
	@echo "... src/AES.s"
	@echo "... src/AVLTree.o"
	@echo "... src/AVLTree.i"
	@echo "... src/AVLTree.s"
	@echo "... src/Bid.o"
	@echo "... src/Bid.i"
	@echo "... src/Bid.s"
	@echo "... src/OMAP.o"
	@echo "... src/OMAP.i"
	@echo "... src/OMAP.s"
	@echo "... src/ORAM.o"
	@echo "... src/ORAM.i"
	@echo "... src/ORAM.s"
	@echo "... src/RAMStore.o"
	@echo "... src/RAMStore.i"
	@echo "... src/RAMStore.s"
	@echo "... test_omap.o"
	@echo "... test_omap.i"
	@echo "... test_omap.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

